import { ProposalData } from './types';

export function calculateLeaseSchedule(
  initialRent: number,
  escalationPercent: number,
  escalationFrequencyYears: number = 5,
  totalYears: number = 30,
  gstPercent: number = 18
) {
  const schedules = [];
  const periods = Math.ceil(totalYears / escalationFrequencyYears);
  let currentRent = initialRent;

  for (let i = 0; i < periods; i++) {
    const startYr = i * escalationFrequencyYears + 1;
    const endYr = Math.min((i + 1) * escalationFrequencyYears, totalYears);
    const months = (endYr - startYr + 1) * 12;

    if (i > 0) {
      currentRent = Math.round(currentRent * (1 + escalationPercent / 100));
    }

    const gstAmount = Math.round((currentRent * gstPercent) / 100);
    const rentInclGst = currentRent + gstAmount;
    const totalPeriodRent = rentInclGst * months;

    schedules.push({
      periodLabel: `[${startYr} - ${endYr}] Years`,
      rentPerMonth: currentRent,
      gstRate: gstPercent,
      gstAmount: gstAmount,
      rentInclGst: rentInclGst,
      months: months,
      totalPeriodRent: totalPeriodRent,
    });
  }

  return schedules;
}

export const sampleProposals: Record<string, ProposalData> = {
  'yerpedu-tirupati': {
    templateRefNo: 'RS-01/A dtd. 01.09.2026',
    documentDate: '08.09.2026',
    proposalTitle: 'Development of new A-site RO under SRMP',
    tenureType: 'Long Term Lease',
    location: 'Yerpedu Bypass on NH-71',
    district: 'Tirupati',
    state: 'Andhra Pradesh',
    category: 'Open (Regular)',

    advtLocationSNo: 'Location S.No. 142',
    advtLocationName: 'Within 3 KMs from Yerpedu Junction on NH-71 towards Renigunta (RHS)',
    annexAdvt: 'Annex-I',
    retailSalesArea: 'Tirupati RSA',
    divisionalOffice: 'Tirupati DO',
    stateOffice: 'TAPSO (Telangana & Andhra Pradesh State Office)',
    srmpYear: '2024-25',
    dateOfAdvertisement: '28.06.2024',
    corrigendumDetails: 'Corrigendum-1 issued on 15.07.2024 for category clarification',
    annexCorrigendum: 'Annex-IA',
    marketType: 'Regular',
    classOfMarket: 'A',
    roadType: 'NH-71 (Four Lane National Highway)',
    corpusFundScheme: 'No',

    selectionMode: 'Draw of Lots held on 18.11.2024',
    bidAmount: 'N/A',
    applicantName: 'Shri K. Venkata Ramana Reddy',
    annexApplication: 'Annex-II',
    constitution: 'Proprietorship',
    ascApprovalDate: '05.12.2024',
    annexAsc: 'Annex-III',
    lecDate: '12.01.2025',
    lecStatus: 'Suitable',
    lecObservations: 'Offered plot meets IOCL NH frontage & depth norms; NHAI sight distance confirmed.',
    annexLec: 'Annex-IV',
    fvcDate: '24.01.2025',
    fvcStatus: 'Suitable',
    fvcObservations: 'Financial & documentary eligibility verified without discrepancy.',
    annexFvc: 'Annex-V',
    loiApprovalDate: '14.02.2025',
    loiComments: 'Approved by ED (RS) without precondition.',
    annexLoiApproval: 'Annex-VI',
    loiDate: '20.02.2025',
    annexLoi: 'Annex-VII',
    addendumLoiDate: 'N/A',
    addendumReason: 'N/A',
    annexAddendum: 'N/A',

    salesFeasibilityBefore: [
      { year: '1st Year', ms: '120', hsd: '240', lubes: '2.50', cng: '0.00', nfr: '1.20' },
      { year: '2nd Year', ms: '150', hsd: '300', lubes: '3.20', cng: '15.00', nfr: '1.80' },
      { year: '3rd Year', ms: '180', hsd: '360', lubes: '3.80', cng: '25.00', nfr: '2.50' },
    ],
    annexFeasibilityBefore: 'Annex-VIII',

    tradingAreaBefore: [
      { omc: 'IOC', rosCount: '2', msVol: '220', hsdVol: '480' },
      { omc: 'BPC', rosCount: '1', msVol: '90', hsdVol: '180' },
      { omc: 'HPC', rosCount: '2', msVol: '160', hsdVol: '340' },
      { omc: 'RBML', rosCount: '1', msVol: '110', hsdVol: '210' },
      { omc: 'NEL', rosCount: '0', msVol: '0', hsdVol: '0' },
      { omc: 'Others', rosCount: '0', msVol: '0', hsdVol: '0' },
      { omc: 'Total', rosCount: '6', msVol: '580', hsdVol: '1210' },
    ],
    annexTradingAreaBefore: 'Annex-IX',
    annexTradingAreaMapBefore: 'Annex-X',

    salesFeasibilityCurrent: [
      { year: '1st Year', ms: '135', hsd: '260', lubes: '2.80', cng: '0.00', nfr: '1.50' },
      { year: '2nd Year', ms: '165', hsd: '320', lubes: '3.50', cng: '20.00', nfr: '2.10' },
      { year: '3rd Year', ms: '195', hsd: '390', lubes: '4.20', cng: '30.00', nfr: '2.80' },
    ],
    annexFeasibilityCurrent: 'Annex-XI',

    tradingAreaCurrent: [
      { omc: 'IOC', rosCount: '2', msVol: '240', hsdVol: '510' },
      { omc: 'BPC', rosCount: '1', msVol: '95', hsdVol: '190' },
      { omc: 'HPC', rosCount: '2', msVol: '175', hsdVol: '360' },
      { omc: 'RBML', rosCount: '1', msVol: '120', hsdVol: '230' },
      { omc: 'NEL', rosCount: '0', msVol: '0', hsdVol: '0' },
      { omc: 'Others', rosCount: '0', msVol: '0', hsdVol: '0' },
      { omc: 'Total', rosCount: '6', msVol: '630', hsdVol: '1290' },
    ],
    annexTradingAreaCurrent: 'Annex-XII',
    annexTradingAreaMapCurrent: 'Annex-XIII',

    reasonSubsequentDev: 'Opening of new Multi-Modal Logistics Park & electronic manufacturing cluster near Renigunta.',
    reasonNewProject: 'Tirupati-Srikalahasti industrial corridor freight corridor widening.',
    reasonHaltingPoint: 'Heavy commercial vehicle halting point adjacent to Indian Oil Truck Parking Node.',
    reasonClosureRO: 'N/A',
    reasonRoadDev: 'Six-laning conversion underway on connecting stretch of NH-71.',
    reasonOther: 'Rapid expansion of Tirupati airport passenger and logistics traffic.',

    landGroup: 'Group 1',
    landDocType: 'Registered Sale Deed No. 4512/2018',
    leaseBalancePeriod: 'Clear Freehold Ownership',
    annexLandDoc: 'Annex-XIV',
    landownerName: 'Shri K. Venkata Ramana Reddy & Smt. K. Sarada Devi',
    relationshipWithApplicant: 'Self & Spouse (LOI Holder)',
    isLoiHolder: 'Yes',
    surveyNo: 'Sy. No. 248/1A, 248/1B',
    surveyRemarks: 'Dry agricultural land converted to Non-Agricultural Commercial vide RDO proceedings dt. 14.10.2024',
    plotFrontage: '45.00',
    plotDepth: '45.00',
    plotAreaSqm: '2025.00',

    negotiationDate: '15.03.2025',
    committeeApprovalDate: '02.03.2025',
    committeeMembers: 'CDRSH (Tirupati DO), Manager (RS-Engg), Law Officer (TAPSO)',
    annexCommittee: 'Annex-XV',
    quotedArea: '2025.00 Sqm',
    quotedAmount: 'Rs. 75,000 / month with 15% escalation every 5 years',
    initialOfferDate: '10.03.2025',
    initialOfferArea: '2025.00 Sqm',
    initialOfferAmount: 'Rs. 65,000 / month',
    initialOfferEscalation: '15% every 5 years',
    annexInitialOffer: 'Annex-XVI',

    valuer1Name: 'Er. P. Subba Rao, Govt Approved Valuer',
    valuer1Date: '25.02.2025',
    valuer1Area: '2025.00',
    valuer1CircleRate: '2800',
    valuer1MarketRate: '4200',
    valuer1PropertyVal: '85,05,000',
    valuer1RentRate: '27.16',
    valuer1MonthlyRent: '55,000',

    valuer2Name: 'M/s S.K. Associates, Chartered Valuation Firm',
    valuer2Date: '27.02.2025',
    valuer2Area: '2025.00',
    valuer2CircleRate: '2800',
    valuer2MarketRate: '4500',
    valuer2PropertyVal: '91,12,500',
    valuer2RentRate: '28.64',
    valuer2MonthlyRent: '58,000',
    annexValuationReport: 'Annex-XVII',

    agreedAreaSqm: '2025.00',
    agreedRentMonthly: '52,000',
    agreedRentPerSqm: '25.68',
    gstStatus: 'Exclusive',
    escalationPercent: '10',
    escalationFrequency: 'Every 5 Years',
    leasePeriodYears: '29 Years 11 Months',
    advancePayment: 'Nil',
    bffAmount: 'N/A',
    annexBff: 'N/A',
    outrightRatePerSqm: 'N/A',
    outrightAmount: 'N/A',
    finalOfferDate: '16.03.2025',
    annexFinalOffer: 'Annex-XVIII',
    committeeNegotiationTerms: 'Agreed at Rs. 52,000/month with 10% escalation every 5 years for 30 years (exclusive of GST 18%). Below both valuers recommended rentals.',
    annexCommitteeReport: 'Annex-XIX',

    titleSearchDate: '18.03.2025',
    annexTitleSearch: 'Annex-XX',
    landOwnershipConfirmed: 'Land is in the registered ownership of LOI Holder & Spouse as per LOI conditions.',
    titleAdvocateConfirmation: 'Sri T. Raghuram, Advocate on IOCL panel, confirmed clear, valid, unencumbered and marketable title with no pending litigation or encumbrance.',
    complaintDetails: 'Nil / Not Applicable. State Office Law verified no complaints against advertisement or LOI.',
    annexComplaint: 'Annex-XXI',
    undertakingDetails: 'Executed 100-rupee stamp undertaking for 30-year lease execution & hand-over of vacant physical possession.',
    annexUndertaking: 'Annex-XXII',

    businessObjectiveText: 'It is proposed to set-up Retail Outlet at Yerpedu Bypass on NH-71, Tirupati District which shall help in expansion of dealer network and mopping up additional sales volume along the bustling Chennai-Tirupati-Bengaluru freight corridor.',

    archetype: 'Type-A Flagship Highway Outlet',
    annexLayout: 'Annex-XXIII',
    layoutDeviation: 'No deviation. Standard IOCL 4-Island NH layout adopted.',
    annexLayoutDeviation: 'N/A',
    additionalAreaDetails: 'None. Offsite area not required.',
    annexAdditionalArea: 'N/A',
    conceptNoteDate: '05.04.2025',
    conceptDeviations: 'Nil. Designed per IOCL Highway Retail Outlet Design Guidelines 2024.',
    annexConcept: 'Annex-XXIV',

    facilitiesTanksDUs: '2 x 20 KL MS (Double Wall FRP jacketed), 2 x 45 KL HSD (UG Tanks), 4 x 4-dispenser Multi-Product Dispensers (MPD)',
    facilitiesInfrastructure: 'RCC Sales Building (G+1), 4-Pump Island 24x18m Overhead Canopy, Hi-Mast Yard Lights, Driveway Pavers, Modern Unisex Toilet Block, NFR C-Store',
    facilitiesDriveway: '60mm Heavy-Duty Interlocking Paver Blocks driveway with 30m deceleration/acceleration lanes and RCC Culvert across NH drain',
    facilitiesElectrical: '45 KVA Dedicated HT Substation, 40 KVA Servo Stabilizer, Dual CVT, 3-Plate Chemical Earthing pits',
    facilitiesRvi: 'Standard IOCL Corporate Identity RVI, 9m Illuminated Monolith, Price Unipole, Directional Signages',
    facilitiesMisc: 'Automated Tank Gauging (ATG), FMS Automation, Air Compressor with digital inflator, 40 KVA Silent DAG DG Set, Water ATM',

    dmDcNocStatus: 'Obtained vide Collector & DM Proc. Dis. No. D3/1182/2025 dt. 20.06.2025',
    nhaiNocStatus: 'Provisional Access Permission granted by PD NHAI PIU-Tirupati dt. 04.05.2025',
    landNaCluStatus: 'Conversion Order issued by Revenue Divisional Officer (RDO) Tirupati dt. 14.10.2024',
    buildingUsePermissionStatus: 'Applied to TUDA (Tirupati Urban Development Authority); Scrutiny completed.',
    siteSpecificPermissionStatus: 'State PWD/Irrigation Dept NOC obtained for approach slab.',
    siteDevMomDate: '15.07.2025',
    siteDevCurrentStatus: 'Site boundary marked; perimeter fencing in progress.',
    annexSiteDev: 'Annex-XXV',
    pesoApprovalRef: 'A/P/HQ/AP/15/8421 (P51402)',
    pesoApprovalDate: '02.08.2025',
    annexPeso: 'Annex-XXVI',

    rationaleSalesPotential: 'High corridor potential with combined volume of 135 KL MS and 260 KL HSD per month in Year 1 growing to 195 KL MS and 390 KL HSD by Year 3.',
    rationaleClearTitle: 'Absolute clear title on freehold plot with 45m NH frontage.',
    rationaleMirr: 'Calculated MIRR is 16.42% against OMC benchmark hurdle rate of 12.00%, ensuring strong capital productivity.',
    rationaleSiteSpecific: 'Strategically located directly opposite upcoming industrial zone with zero IOCL presence within 4 km radius.',
    rationaleOthers: 'Provides vital strategic containment against private competitors (RBML & Shell) on NH-71.',

    exceptionFacilities: 'Provision of 2x45 KL HSD tanks justified due to heavy commercial long-haul fleet demand as per Policy 152-06/2009.',
    exceptionCanopyRvi: 'Standard Canopy & RVI provided as per Policy 174-08/2010.',
    exceptionLayout: 'N/A - Standard layout followed.',
    exceptionOther: 'Nil.',

    leaseSchedules: calculateLeaseSchedule(52000, 10, 5, 30, 18),

    stampDuty: 'Rs. 2,85,000 (As per AP Stamp & Registration Act)',
    registrationCharges: 'Rs. 58,000',
    legalMiscExpenses: 'Rs. 45,000 (Title opinion, documentation & encumbrance certificate charges)',

    materialCostLacs: '95.40',
    constructionCostLacs: '68.20',
    contingencyCostLacs: '8.18',
    statutoryCostLacs: '7.50',
    totalBeLacs: '179.28',
    annexTotalBe: 'Annex-XXVII',

    mirrRefNo: 'MIRR/TAPSO/TPT/2025-26/089',
    annexMirrRef: 'Annex-XXVIII',
    calculatedMirrPercent: '16.42',
    sensitivityMirrPercent: '13.85',
    mirrBenchmarkMet: 'Yes',
    bffApplicability: 'No',

    advocateFeesExpenses: '45,000',
    registrationStampExp: '3,43,000',
    grossRentalOutgo: '3,57,48,720',
  },

  'chandragiri-chittoor': {
    templateRefNo: 'RS-01/A dtd. 01.09.2026',
    documentDate: '08.09.2026',
    proposalTitle: 'Development of new A-site RO under SRMP',
    tenureType: 'Long Term Lease',
    location: 'Chandragiri Bypass on SH-61',
    district: 'Chittoor',
    state: 'Andhra Pradesh',
    category: 'OBC (Rural/Kisan Seva Kendra)',

    advtLocationSNo: 'Location S.No. 88',
    advtLocationName: 'Chandragiri town limits towards Chittoor on SH-61 (LHS)',
    annexAdvt: 'Annex-I',
    retailSalesArea: 'Chittoor RSA',
    divisionalOffice: 'Tirupati DO',
    stateOffice: 'TAPSO',
    srmpYear: '2024-25',
    dateOfAdvertisement: '28.06.2024',
    corrigendumDetails: 'Nil',
    annexCorrigendum: 'N/A',
    marketType: 'Rural',
    classOfMarket: 'D1',
    roadType: 'SH-61 (State Highway)',
    corpusFundScheme: 'No',

    selectionMode: 'Draw of Lots held on 22.11.2024',
    bidAmount: 'N/A',
    applicantName: 'Smt. M. Hemalatha',
    annexApplication: 'Annex-II',
    constitution: 'Proprietorship',
    ascApprovalDate: '10.12.2024',
    annexAsc: 'Annex-III',
    lecDate: '18.01.2025',
    lecStatus: 'Suitable',
    lecObservations: 'Offered plot dimension 35m x 35m compliant with SH rural outlet standards.',
    annexLec: 'Annex-IV',
    fvcDate: '29.01.2025',
    fvcStatus: 'Suitable',
    fvcObservations: 'All educational and financial credentials in order.',
    annexFvc: 'Annex-V',
    loiApprovalDate: '20.02.2025',
    loiComments: 'Approved by SRH without observation.',
    annexLoiApproval: 'Annex-VI',
    loiDate: '28.02.2025',
    annexLoi: 'Annex-VII',
    addendumLoiDate: 'N/A',
    addendumReason: 'N/A',
    annexAddendum: 'N/A',

    salesFeasibilityBefore: [
      { year: '1st Year', ms: '65', hsd: '110', lubes: '1.20', cng: '0.00', nfr: '0.50' },
      { year: '2nd Year', ms: '80', hsd: '135', lubes: '1.50', cng: '0.00', nfr: '0.80' },
      { year: '3rd Year', ms: '95', hsd: '160', lubes: '1.80', cng: '0.00', nfr: '1.10' },
    ],
    annexFeasibilityBefore: 'Annex-VIII',

    tradingAreaBefore: [
      { omc: 'IOC', rosCount: '1', msVol: '55', hsdVol: '95' },
      { omc: 'BPC', rosCount: '1', msVol: '60', hsdVol: '105' },
      { omc: 'HPC', rosCount: '1', msVol: '70', hsdVol: '115' },
      { omc: 'RBML', rosCount: '0', msVol: '0', hsdVol: '0' },
      { omc: 'NEL', rosCount: '0', msVol: '0', hsdVol: '0' },
      { omc: 'Others', rosCount: '0', msVol: '0', hsdVol: '0' },
      { omc: 'Total', rosCount: '3', msVol: '185', hsdVol: '315' },
    ],
    annexTradingAreaBefore: 'Annex-IX',
    annexTradingAreaMapBefore: 'Annex-X',

    salesFeasibilityCurrent: [
      { year: '1st Year', ms: '70', hsd: '120', lubes: '1.40', cng: '0.00', nfr: '0.60' },
      { year: '2nd Year', ms: '85', hsd: '145', lubes: '1.70', cng: '0.00', nfr: '0.90' },
      { year: '3rd Year', ms: '105', hsd: '175', lubes: '2.00', cng: '0.00', nfr: '1.30' },
    ],
    annexFeasibilityCurrent: 'Annex-XI',

    tradingAreaCurrent: [
      { omc: 'IOC', rosCount: '1', msVol: '60', hsdVol: '100' },
      { omc: 'BPC', rosCount: '1', msVol: '65', hsdVol: '110' },
      { omc: 'HPC', rosCount: '1', msVol: '75', hsdVol: '120' },
      { omc: 'RBML', rosCount: '0', msVol: '0', hsdVol: '0' },
      { omc: 'NEL', rosCount: '0', msVol: '0', hsdVol: '0' },
      { omc: 'Others', rosCount: '0', msVol: '0', hsdVol: '0' },
      { omc: 'Total', rosCount: '3', msVol: '200', hsdVol: '330' },
    ],
    annexTradingAreaCurrent: 'Annex-XII',
    annexTradingAreaMapCurrent: 'Annex-XIII',

    reasonSubsequentDev: 'Expansion of horticulture cold storage and agro-processing hubs in Chandragiri mandal.',
    reasonNewProject: 'Establishment of regional mango pulp processing units.',
    reasonHaltingPoint: 'Tractor and farm machinery convergence center.',
    reasonClosureRO: 'N/A',
    reasonRoadDev: 'SH-61 strengthening and bypass connecting to Palamaner.',
    reasonOther: 'Rapid agrarian mechanization in surrounding 12 revenue villages.',

    landGroup: 'Group 1',
    landDocType: 'Registered Gift Deed No. 1208/2021',
    leaseBalancePeriod: 'Clear Freehold Ownership',
    annexLandDoc: 'Annex-XIV',
    landownerName: 'Smt. M. Hemalatha',
    relationshipWithApplicant: 'Self (LOI Holder)',
    isLoiHolder: 'Yes',
    surveyNo: 'Sy. No. 112/3',
    surveyRemarks: 'Dry patta land converted for Non-Agricultural purpose.',
    plotFrontage: '35.00',
    plotDepth: '35.00',
    plotAreaSqm: '1225.00',

    negotiationDate: '24.03.2025',
    committeeApprovalDate: '10.03.2025',
    committeeMembers: 'CDRSH (Tirupati DO), Manager (RS-Engg), Finance Officer',
    annexCommittee: 'Annex-XV',
    quotedArea: '1225.00 Sqm',
    quotedAmount: 'Rs. 40,000 / month with 15% escalation every 5 years',
    initialOfferDate: '18.03.2025',
    initialOfferArea: '1225.00 Sqm',
    initialOfferAmount: 'Rs. 35,000 / month',
    initialOfferEscalation: '15% every 5 years',
    annexInitialOffer: 'Annex-XVI',

    valuer1Name: 'Er. C. Madhava, Govt Approved Valuer',
    valuer1Date: '05.03.2025',
    valuer1Area: '1225.00',
    valuer1CircleRate: '1500',
    valuer1MarketRate: '2200',
    valuer1PropertyVal: '26,95,000',
    valuer1RentRate: '22.04',
    valuer1MonthlyRent: '27,000',

    valuer2Name: 'M/s Venkateswara Valuations',
    valuer2Date: '08.03.2025',
    valuer2Area: '1225.00',
    valuer2CircleRate: '1500',
    valuer2MarketRate: '2400',
    valuer2PropertyVal: '29,40,000',
    valuer2RentRate: '23.67',
    valuer2MonthlyRent: '29,000',
    annexValuationReport: 'Annex-XVII',

    agreedAreaSqm: '1225.00',
    agreedRentMonthly: '26,000',
    agreedRentPerSqm: '21.22',
    gstStatus: 'Exclusive',
    escalationPercent: '10',
    escalationFrequency: 'Every 5 Years',
    leasePeriodYears: '29 Years 11 Months',
    advancePayment: 'Nil',
    bffAmount: 'N/A',
    annexBff: 'N/A',
    outrightRatePerSqm: 'N/A',
    outrightAmount: 'N/A',
    finalOfferDate: '25.03.2025',
    annexFinalOffer: 'Annex-XVIII',
    committeeNegotiationTerms: 'Agreed at Rs. 26,000/month with 10% escalation every 5 years for 30 years (exclusive of GST 18%). Below both valuers recommendations.',
    annexCommitteeReport: 'Annex-XIX',

    titleSearchDate: '28.03.2025',
    annexTitleSearch: 'Annex-XX',
    landOwnershipConfirmed: 'Land is in exclusive ownership and possession of LOI Holder.',
    titleAdvocateConfirmation: 'Panel advocate Sri P. Sreenivasulu confirmed clear and marketable title.',
    complaintDetails: 'Nil. No legal dispute exists.',
    annexComplaint: 'Annex-XXI',
    undertakingDetails: 'Executed undertaking as per standard format.',
    annexUndertaking: 'Annex-XXII',

    businessObjectiveText: 'It is proposed to set-up Retail Outlet at Chandragiri Bypass on SH-61, Chittoor District which shall help in expansion of dealer network and mopping up additional sales volume in rural and agrarian trading cluster.',

    archetype: 'Type-C Rural Kisan Seva Kendra Outlet',
    annexLayout: 'Annex-XXIII',
    layoutDeviation: 'Nil. Standard KSK layout.',
    annexLayoutDeviation: 'N/A',
    additionalAreaDetails: 'None.',
    annexAdditionalArea: 'N/A',
    conceptNoteDate: '12.04.2025',
    conceptDeviations: 'Nil.',
    annexConcept: 'Annex-XXIV',

    facilitiesTanksDUs: '1 x 20 KL MS, 1 x 20 KL HSD, 2 x 2-dispenser Multi-Product Dispensers',
    facilitiesInfrastructure: 'Kisan Kendra Sales Building, 2-Pump Island Cantilever Canopy, Paver Block Driveway, Modern Toilet block, Agro-service retail corner',
    facilitiesDriveway: 'Heavy duty concrete pavers, approach culvert over road drain',
    facilitiesElectrical: '25 KVA Commercial connection, Servo stabilizer, Chemical Earthing',
    facilitiesRvi: 'Standard IOCL Rural KSK Visual Identity elements & Monolith',
    facilitiesMisc: 'FMS Automation, Air inflator, 25 KVA Silent DG set, Drinking water kiosk',

    dmDcNocStatus: 'Obtained vide Collector Proc. D.Dis. 542/2025 dt. 12.05.2025',
    nhaiNocStatus: 'N/A (State Highway road under State R&B Dept; R&B permission obtained)',
    landNaCluStatus: 'RDO conversion issued dt. 18.01.2025',
    buildingUsePermissionStatus: 'Grama Panchayat approval obtained',
    siteSpecificPermissionStatus: 'Gram Panchayat NOC on record',
    siteDevMomDate: '10.06.2025',
    siteDevCurrentStatus: 'Site levelling completed; construction ready.',
    annexSiteDev: 'Annex-XXV',
    pesoApprovalRef: 'A/P/HQ/AP/15/9012 (P62100)',
    pesoApprovalDate: '28.06.2025',
    annexPeso: 'Annex-XXVI',

    rationaleSalesPotential: 'High rural diesel and agri-tractor demand of 70 KL MS and 120 KL HSD growing to 105 KL MS and 175 KL HSD.',
    rationaleClearTitle: 'Unencumbered registered title with clear road frontage.',
    rationaleMirr: 'Yields healthy MIRR of 15.18% surpassing 12% benchmark.',
    rationaleSiteSpecific: 'Only automated fueling station within 6 km rural radius.',
    rationaleOthers: 'Strengthens rural market leadership under Corporate Social Responsibility & rural reach.',

    exceptionFacilities: 'Single 20 KL tank for MS and HSD as per Rural KSK Policy 226-12/2015.',
    exceptionCanopyRvi: 'Cantilever canopy provided as per Policy 174-08/2010.',
    exceptionLayout: 'N/A',
    exceptionOther: 'Nil.',

    leaseSchedules: calculateLeaseSchedule(26000, 10, 5, 30, 18),

    stampDuty: 'Rs. 1,42,000',
    registrationCharges: 'Rs. 32,000',
    legalMiscExpenses: 'Rs. 35,000',

    materialCostLacs: '62.50',
    constructionCostLacs: '44.80',
    contingencyCostLacs: '5.36',
    statutoryCostLacs: '5.20',
    totalBeLacs: '117.86',
    annexTotalBe: 'Annex-XXVII',

    mirrRefNo: 'MIRR/TAPSO/TPT/2025-26/112',
    annexMirrRef: 'Annex-XXVIII',
    calculatedMirrPercent: '15.18',
    sensitivityMirrPercent: '12.92',
    mirrBenchmarkMet: 'Yes',
    bffApplicability: 'No',

    advocateFeesExpenses: '35,000',
    registrationStampExp: '1,74,000',
    grossRentalOutgo: '1,78,74,360',
  },
};
